name: cron

on:
  schedule:
    - cron: "0 3 * * 1"
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v2

      - name: docker build
        run: docker build cron -t docker.pkg.github.com/docker/cron

      - name: docker login
        run: echo "${{ secrets.GIT_HUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: docker push
        run: docker push docker.pkg.github.com/docker/cron
