name: Docker build schedule

on:
  schedule:
  - cron:  '0 3 * * 1'
  push:
    branches: 
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Build
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        IMAGE="aczigler/cron:latest"
        docker build . --file Dockerfile --tag $IMAGE
        echo $DOCKER_TOKEN | docker login docker.pkg.github.com --username "$DOCKER_USER" --password-stdin
        docker push $IMAGE
