name: Docker build schedule

on:
  schedule:
  - cron:  '0 3 * * 1'
  push:
    branches: 
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Build
      run: |
        IMAGE="docker.pkg.github.com/alexanderczigler/docker-cron/docker-cron:latest"
        docker build . --file Dockerfile --tag $IMAGE
        echo $DOCKER_TOKEN | docker login docker.pkg.github.com --username alexanderczigler --password-stdin
        docker push $IMAGE
