name: docker

on:
  schedule:
  - cron:  '0 3 * * 1'
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: clone
      uses: actions/checkout@v2

    - name: docker login
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
      run: echo $DOCKER_TOKEN | docker login --username "$DOCKER_USER" --password-stdin

    - name: docker build
      run: docker build . --file Dockerfile --tag aczigler/cron:latest
        
    - name: docker push
      run: docker push aczigler/cron:latest