name: postgres-backup

on:
  schedule:
    - cron: "0 3 * * *"
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v2

      - name: docker build
        run: docker build postgres-backup -t aczigler/postgres-backup:latest

      - name: docker login
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: echo $DOCKER_TOKEN | docker login --username "$DOCKER_USER" --password-stdin

      - name: docker push
        run: docker push aczigler/postgres-backup:latest
