name: Build & publish packages

on:
  schedule:
    - cron: "0 3 * * 1"
  push:
    branches:
      - master

jobs:

  cron:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v2

      - name: docker build
        run: docker build cron -t iteamacr/cron

      - name: docker push
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: |
          echo $DOCKER_TOKEN | docker login --username "$DOCKER_USER" --password-stdin
          docker push iteamacr/cron

  node-alpine-builder:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v2

      - name: docker build
        run: |
          docker build node-alpine-builder --build-arg NODE_VERSION=12 -t iteamacr/node-alpine-builder:12
          docker build node-alpine-builder --build-arg NODE_VERSION=13 -t iteamacr/node-alpine-builder:13
          docker build node-alpine-builder --build-arg NODE_VERSION=14 -t iteamacr/node-alpine-builder:14
          docker build node-alpine-builder --build-arg NODE_VERSION=15 -t iteamacr/node-alpine-builder:15
          docker build node-alpine-builder --build-arg NODE_VERSION=16 -t iteamacr/node-alpine-builder:16
          docker tag iteamacr/node-alpine-builder:16 iteamacr/node-alpine-builder:latest

      - name: docker push
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: |
          echo $DOCKER_TOKEN | docker login --username "$DOCKER_USER" --password-stdin
          docker push iteamacr/node-alpine-builder:12
          docker push iteamacr/node-alpine-builder:13
          docker push iteamacr/node-alpine-builder:14
          docker push iteamacr/node-alpine-builder:15
          docker push iteamacr/node-alpine-builder:16
          docker push iteamacr/node-alpine-builder:latest

  node-full-icu:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v2

      - name: docker build
        run: |
          docker build node-full-icu --build-arg NODE_VERSION=12 -t iteamacr/node-full-icu:12
          docker build node-full-icu --build-arg NODE_VERSION=13 -t iteamacr/node-full-icu:13
          docker build node-full-icu --build-arg NODE_VERSION=14 -t iteamacr/node-full-icu:14
          docker build node-full-icu --build-arg NODE_VERSION=15 -t iteamacr/node-full-icu:15
          docker build node-full-icu --build-arg NODE_VERSION=16 -t iteamacr/node-full-icu:16
          docker tag iteamacr/node-full-icu:16 iteamacr/node-full-icu:latest

      - name: docker push
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: |
          echo $DOCKER_TOKEN | docker login --username "$DOCKER_USER" --password-stdin
          docker push iteamacr/node-full-icu:12
          docker push iteamacr/node-full-icu:13
          docker push iteamacr/node-full-icu:14
          docker push iteamacr/node-full-icu:15
          docker push iteamacr/node-full-icu:16
          docker push iteamacr/node-full-icu:latest

  postgres-backup:
    needs: cron
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v2

      - name: docker build
        run: |
          docker build postgres-backup -t iteamacr/postgres-backup:latest
          docker tag iteamacr/postgres-backup:latest iteamacr/postgres-backup:buster
          echo "* * * * * /bin/sh /backup.sh >> /var/log/cron.log" > postgres-backup/crontab
          echo "* * * * * /bin/sh /sync.sh >> /var/log/cron.log" >> postgres-backup/crontab
          echo "# empty line" >> postgres-backup/crontab
          docker build postgres-backup -t iteamacr/postgres-backup:every-minute

      - name: docker push
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: |
          echo $DOCKER_TOKEN | docker login --username "$DOCKER_USER" --password-stdin
          docker push iteamacr/postgres-backup:buster
          docker push iteamacr/postgres-backup:latest
          docker push iteamacr/postgres-backup:every-minute
